CREATE DATABASE IF NOT EXISTS dogs;

USE dogs;

CREATE TABLE IF NOT EXISTS dog (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    breedId INT UNSIGNED REFERENCES breed(id),
    name VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS breed (
    id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(60) NOT NULL
);